name: HTTPX

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run build
        run: go build

      - name: Run gofmt, vet & lint
        run: |
          ./ci/validate-gofmt.sh
          go vet .
          GO111MODULE=off go get -u golang.org/x/lint/golint
          ./ci/validate-lint.sh

      - name: Run testing
        run: go test
