---
name: CI
defaults:
  run:
    shell: bash
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: false
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: .
          strict: true
          no_warnings: false
          config_file: .yamllint
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: -s bash
        with:
          format: tty
  ci:
    uses: kare/github/.github/workflows/go-pkg-ci.yaml@main
