---
name: Release created
on:
  release:
    types:
      - created
jobs:
  released:
    uses: kare/github/.github/workflows/go-release.yaml@main
    inputs:
      go_modules_path: ${{ github.repository }}
      version: ${{ github.event.release.tag_name }}
